build:
  version: 1.0

loans:
  message: "Welcome to EazyBank loans related local qa APIs"
  contactDetails:
    name: "Akash - Developer"
    email: "akash@eazybank.com"
  onCallSupport:
    -(555) 555-7777
    -(555) 523-4444