spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
#          uri: "https://github.com/eazybytes/eazybytes-config.git"
          uri: "https://github.com/UjjwalRohilla/microservice_practice-configserver.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071